---
title: "Cell Type Identification"
description: |
  This script is used to perform the following
  1. Integrate the data from all brain regions for all donors using rPCA integration
  2. Perform clustering
  3. Identify markers to annotate clustering
output: 
  distill::distill_article
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)

```

# Dependencies


```{r Dependencies}

#Load requisite packages.
require(Seurat)
require(data.table)
require(tidyverse)
require(ggpubr)
require(cowplot)
library(SeuratWrappers)
library(rstatix)
library(RColorBrewer)
library(doParallel)
library(foreach)

#source external dependancies
source("Helper_scripts/figure_themes.R")
```


```{r rPCA integration}

rdata_path_in <- "../data/Rdata/in"
rdata_path_out <-  "./data/Rdata/out/"
scripts_path <- "../scripts/"
results_path <- "../results/"


brain_regions <- c("BA20", "BA46", "EC", "V1", "V2")

# Use 4 cores

ncore <- 4

#select <- dplyr::select
#theme_set(theme_cowplot())

# function to integrate the data

#' @param seurat.obj Input Seurat object
#' @param brain_region Brain region, e.g. BA46
#' @param rdata_file_out path to output .Rdata file
#' @param regress_vars variables to regress out
#' @param n_HVGs Number of highly-variable genes
process_and_integrate_raw_data <- function(seurat.obj, 
                                           brain_region, 
                                           rdata_file_out, 
                                           regress_vars=c("nCount_RNA", "percent.mito"), 
                                           n_HVGs=2000 
) {
  # Split Seurat data by donor ID
  seurat_split <- SplitObject(seurat.obj, split.by="Donor.ID")
  rm(seurat.obj)

  # normalize (log normalization) and identify high variable features for each Donor 
  cat("\nNormalizing data\n")
  seurat_split <- lapply(X = seurat_split, FUN = function(x) {
    x <- NormalizeData(x, verbose=F) 
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = n_HVGs,
                              verbose=F) 
  })

  # Save the data
  save(seurat_split, file=rdata_out_file)

  # select features that are repeatedly variable across datasets for integration run PCA on each
  # dataset using these features
  cat("\nSelecting integration features\n")
  anchor_features <- SelectIntegrationFeatures(object.list = seurat_split, nfeatures = n_HVGs)
  seurat_split <- lapply(X = seurat_split, FUN = function(x) {
    x <- ScaleData(x, features = anchor_features, verbose = F)
    x <- RunPCA(x, features = anchor_features, verbose = F)
  })

  # Perform integration using reciprocal PCA (rPCA)
  cat("\nFinding integration anchors\n")
  integration_anchors = FindIntegrationAnchors(object.list = seurat_split,
                                               anchor.features = anchor_features,
                                               reduction = "rpca")

  # this command creates an 'integrated' data assay
  seurat_proc <- IntegrateData(anchorset = integration_anchors)

  # Save the integrated data
  save(seurat_proc, file=rdata_file_out)

  # Specify that the next analyses should be on the integrated assay
  DefaultAssay(seurat_proc) <- "integrated"

  # scale integrated data and run regular PCA for dimensionality reduction
  cat("\nScaling integrated data and performing PCA\n")
  seurat_proc <- ScaleData(seurat_proc, verbose = T, vars.to.regress = regress_vars)
  seurat_proc <- RunPCA(seurat_proc, npcs = 50, verbose = F)

  # UMAP nonlinear dimension reduction
  seurat_proc <- RunUMAP(seurat_proc, reduction = "pca", dims = 1:30)

  # Graph-based neighbor detection
  seurat_proc <- FindNeighbors(seurat_proc, reduction = "pca", dims = 1:30)

  # Identify clusters at resolutions 0.1 through 1.0
  seurat_proc <- FindClusters(seurat_proc, resolution = seq(0.1, 1, by=0.1))

  # Assign brain region name to variable and save
  assign(paste0(brain_region, "_rPCA"), seurat_proc)
  save(list=ls(pattern=("_rPCA")), file=rdata_file_out)

  # Clean up workspace
  rm(seurat_proc)

}

# Calling the function process_and_integrate_raw_data
# Iterate over our brain regions

for (brain_region in c("BA46", "V1", "V2")) {
  print(sprintf("Now starting %s", brain_region))

  # Define input and output Rdata files
  rdata_in_file <- paste0(rdata_path_in, sprintf("%s_preprocessed.Rdata", brain_region)) # raw data
  rdata_out_file <- paste0(rdata_path_out, sprintf("%s_rPCA_new.Rdata", brain_region)) # integrated data

  if (!file.exists(rdata_out_file)) {
    print(sprintf("Now processing %s", brain_region))

    # Load raw snRNAseq data
    load(rdata_in_file)

    # Run rPCA integration function on data for current brain region
    process_and_integrate_raw_data(seurat.obj=get(brain_region),
                                   brain_region=brain_region,
                                   rdata_file_out=rdata_out_file,
                                   regress_vars=regress_vars,
                                   n_HVGs=2000)
  }
}

#Entorhinal cortex data was already integrated; copied from data/Rdata/EC_rPCA-clear-preprocessed.RData

```


```{r Annotate cell clusters based on markers}
# Find all markers for each brain region of the integrated data

#' find all markers
#' @param seurat.obj seurat object;
#' @param res numeric; resolution
#' @param ncore numeric; number of core to use
#' @param known_marker_genes vector; list of known marker genes
find_all_markers = function(seurat.obj, res, ncore=1, known_marker_genes){
  DefaultAssay(seurat.obj) = "RNA"
  Idents(seurat.obj) = paste0("integrated_snn_res.", res)
  
  cat("identify subcluster markers\n")
  if(ncore!=1){
    suppressMessages({
      plan("multiprocess", workers = ncore)
      options(future.globals.maxSize= 891289600)
      options(future.seed = TRUE)
      plan()
    })
  }
  ### Warning message:
  ### glm.fit: fitted probabilities numerically 0 or 1 occurred
  ### https://www.biostars.org/p/404577/
  markers = FindAllMarkers(seurat.obj, test.use = "LR",
                           latent.vars = c("Donor.ID"))
  plan("sequential")
  
  return(markers)
}

#calling the function
for (brain_region in c("BA20", "BA46", "EC", "V1", "V2")) {
  print(sprintf("Now starting %s", brain_region))

  # Define input and output Rdata files
  rdata_in_file <- paste0(rdata_path_in, sprintf("%s_preprocessed.Rdata", brain_region)) # raw data
  rdata_out_file <- paste0(rdata_path_out, sprintf("%s_rPCA_new.Rdata", brain_region)) # integrated data

  if (!file.exists(rdata_out_file)) {
    print(sprintf("Now processing %s", brain_region))

    # Load raw snRNAseq data
    load(rdata_in_file)
    ncore = 4
    for (res in seq(0.1, 1, 0.1)){
    # Run find_all_markers
    markers = find_all_markers(rdata_in_file, res, ncore)
    fwrite(markers, file.path = paste0(results_path, res, brain_region, "markers.csv"))
    }
  }
}
```



```{r Fig 1}

#' @param obj Seurat object
#' @param region string; brain region (as figure title)
#' @param show_label T/F; show label or not; default = F
#' @return ggplot object of dim plot

dim_plot = function(obj, region, show_label = T){
  p = DimPlot(obj, size = size, raster = F, label = show_label, group.by = "celltype") +
      umap_theme() +
      scale_color_manual(
        values = c(
          "astrocytes" = "#F38181", 
          "microglia" = "#A3DE83", 
          "endothelial" = "#FCE38A", 
          "neurons" = "#EA99D5", 
          "oligodendrocytes" = "#8BDBF5"
      )) +
    labs(title = region)
  return(p)
}


#' custom function for figure 1c
#' @param obj seurat object
#' @param genes vector; genes in violin plots
#' @return ggplot object

vlnplot = function(obj, genes){
  DefaultAssay(obj) = "RNA"
  obj@active.ident  = factor(
    obj$celltype,
    levels = c("astrocytes", "microglia", "endothelial","neurons", "oligodendrocytes"))
  p = VlnPlot(
    obj, 
    features = genes, 
    stack = TRUE, sort = FALSE, flip = TRUE
  ) +
    scale_fill_manual(
      values = c(
        # astrocytes
        "ADGRV1" = "#F38181", 
        "ALDH1L1" = "#F38181", 
        "AQP4" = "#F38181",
        "GFAP" = "#F38181",
        # microglia
        "CD74" = "#A3DE83", 
        "P2RY12" = "#A3DE83", 
        # endothelial
        "CLDN5" = "#FCE38A", 
        "VWF" = "#FCE38A", 
        # neurons
        "GRIA1" = "#EA99D5", 
        "GRIK2" = "#EA99D5", 
        # oligodendrocytes
        "MOBP" = "#8BDBF5", 
        "PLP1" = "#8BDBF5"
      )) +
    theme(
      legend.position = 'none',
      axis.title.x=element_blank(),
      plot.background = element_rect(
        fill = "white", 
        color = NA
      ))
  return(p)
}


# marker genes for using in the violin plots (Fig 1c)
markers = fread(file.path("..","..","/Data/celltype_markers_ASP.csv"))
vlnplot_genes = c("ADGRV1", "ALDH1L1", "AQP4", "GFAP",
                  "CD74", "P2RY12","VWF", "CLDN5")
vlnplot_genes = markers[gene %in% vlnplot_genes, ]
vlnplot_genes[, celltype := factor(celltype, 
      levels = c("Astrocytes", "Microglia", "Endothelial", 
                  "Neurons", "Oligodendrocytes"))]
vlnplot_genes = vlnplot_genes[order(celltype), ]
vlnplot_genes[, gene := factor(gene, levels = vlnplot_genes$gene)]
```


#EC
```{r}
# load data
load(file.path("..", "Data/Fig1_data/EC_subset.RData"))
EC_subset$celltype = factor(
  EC_subset$Annie_Cell_Type, 
  labels = c("astrocytes", "endothelial", "microglia", 
             "neurons", "oligodendrocytes")
)
Idents(EC_subset) = "celltype"
EC_subset = EC_subset[, !Idents(EC_subset) %in% c("unknown")]

# umap
p_umap_EC = dim_plot(EC_subset,"EC")

# violin plot
p_vln_EC = vlnplot(
  obj = EC_subset, 
  genes = vlnplot_genes$gene
)

fig1bc_EC = ggarrange(
  p_umap_EC,
  p_vln_EC,
  ncol = 1, nrow = 2,
  heights = c(1, 1.7)
)

# ggsave(fig1bc_EC, filename = "~/Dropbox (Partners HealthCare)/Abbvie collaboration/Astrocytes scripts/Results/Figure_1/figure1b&1c_EC.png", 
#     height = 10, width = 4)
rm(EC_subset)
```


#ITG
```{r}
# load data
load(file.path("..", "Data/Fig1_data/ITG_subset.RData"))
Idents(rPCA) = "celltype"
rPCA = rPCA[, !Idents(rPCA) %in% c("unknown")]

# umap
p_umap_ITG = dim_plot(
  obj = ITG_subset, 
  region = "ITG"
)
# ggsave(p_umap_ITG, filename = "fig1b_BA20.png", width = 4, height = 4)

# violin plot
p_vln_ITG = vlnplot(
  obj = ITG_subset, 
  genes = vlnplot_genes$gene
)
# ggsave(p, filename = file.path(p_dir, "fig1c_ITG.pdf")), height = 7, width = 4)

fig1bc_ITG = ggarrange(
  p_umap_ITG,
  p_vln_ITG,
  ncol = 1, nrow = 2,
  heights = c(1, 1.7)
)
# ggsave(fig1bc_ITG, filename = file.path(p_dir, "figure1b&1c_ITG.png"), 
#       height = 10, width = 4)
rm(rPCA)
```

## PFC (BA46)

```{r}
# load data
#Note the data loaded here is the subset of data 

load(file.path("..","Data/Fig1_data/BA46_subset.RData"))
BA46_subset$celltype = factor(
  BA46_subset$Annie_Cell_Type, 
  labels = c("astrocytes", "endothelial", "microglia", 
             "neurons", "oligodendrocytes")
)
Idents(BA46_rPCA) = "celltype"
BA46_rPCA = BA46_rPCA[, Idents(BA46_rPCA) != "unknown"]

# umap
p_umap_PFC = dim_plot(
  obj = BA46_subset, 
  region = "PFC"
)
# ggsave(p_EC, filename = file.path(p_dir, "fig1b_PFC.png"), width = 4, height = 4)

# violin plot
p_vln_PFC = vlnplot(
  obj = BA46_subset, 
  genes = vlnplot_genes$gene
)
# ggsave(p, filename = file.path(p_dir, "fig_1c_PFC.pdf"), height = 7, width = 4)

fig1bc_PFC = ggarrange(
  p_umap_PFC,
  p_vln_PFC,
  ncol = 1, nrow = 2,
  heights = c(1, 1.7)
)
# ggsave(fig1bc_PFC, filename = "~/Dropbox (Partners HealthCare)/Abbvie collaboration/Astrocytes scripts/Results/Figure_1/figure1b&1c_PFC.png"), 
#        height = 10, width = 4)
rm(BA46_rPCA)
```

## V2

```{r}
load data
load(file.path("..","Data/Fig1_data/V2_subset.RData"))
V2_subset$celltype = factor(V2_subset$Annie_Cell_Type, 
       labels = c("astrocytes", "endothelial", "microglia", 
                  "neurons", "oligodendrocytes"))
Idents(V2_rPCA) = "celltype"
V2_rPCA = V2_rPCA[, Idents(V2_rPCA) != "unknown"]

# umap
p_umap_V2 = dim_plot(
  obj = V2_subset, 
  region = "V2"
)
# ggsave(p_EC, filename = file.path(p_dir, "fig1b_V2.png"), width = 4, height = 4)

# violin plot
p_vln_V2 = vlnplot(
  obj = V2_subset, 
  genes = vlnplot_genes$gene
)
# ggsave(p, filename = file.path(p_dir, "fig_1c_V2.pdf"), height = 7, width = 4)

fig1bc_V2 = ggarrange(
  p_umap_V2,
  p_vln_V2,
  ncol = 1, nrow = 2,
  heights = c(1, 1.7)
)
# ggsave(fig1bc_V2, filename = "~/Dropbox (Partners HealthCare)/Abbvie collaboration/Astrocytes scripts/Results/Figure_1/figure1b&1c_V2.png"), 
#        height = 10, width = 4)
rm(V2_rPCA)
```

## V1

```{r}
load(file.path("..","Data/Fig1_data/V1_subset.RData"))
V1_subset$celltype = factor(V1_subset$Annie_Cell_Type, 
       labels = c("astrocytes", "endothelial", "microglia", 
                  "neurons", "oligodendrocytes","unknown"))
Idents(V1_subset) = "celltype"
V1_subset = V1_subset[, Idents(V1_subset) != "unknown"]

# umap
p_umap_V1 = dim_plot(
  obj = V1_subset, 
  region = "V1"
)
# ggsave(p_EC, filename = file.path(p_dir, "fig1b_V1.png"), width = 4, height = 4)

# violin plot
p_vln_V1 = vlnplot(
  obj = V1_subset, 
  genes = vlnplot_genes$gene
)
# ggsave(p, filename = file.path(p_dir, "fig_1c_V1.pdf"), height = 7, width = 4)

fig1bc_V1 = ggarrange(
  p_umap_V1,
  p_vln_V1,
  ncol = 1, nrow = 2,
  heights = c(1, 1.7)
)
#ggsave(fig1bc_V1, filename = "~/Dropbox (Partners HealthCare)/Abbvie collaboration/Astrocytes scripts/Results/Figure_1/figure1b&1c_V1.png"), 
#       height = 10, width = 4)
rm(V1_rPCA)
```


