library(gtools)

#' barplot of count table {table()}
#' @param n_table matrix; generated by table()
#' @param xlab string; x axis title
#' @param ylab string; y axis title
#' @param legendlab string; legend title
#' @param pct logical; whether plot percentage or not
freq_barplot = function(n_table, xlab = NULL, ylab = NULL, 
                        legendlab = NULL, pct = T,
                        sort.numeric = T, annot = T, 
                        p_annot_label="", rotate.x = F){
  ## annotation plot
  p_annot = subc_statis_test(t(n_table), label = p_annot_label)
  
  ## expected proportion
  ep = colSums(n_table)/sum(rowSums(n_table))
  if(pct == T){
    p_e = ggplot(data.table(group = names(ep), 
                            expected_p = ep, 
                            x = "expected proportion"), 
                 aes(x = x, y = expected_p, fill = group)) +
      geom_bar(stat="identity", color = "black") +
      theme_minimal_hgrid(12) +
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            legend.position = "none",
            plot.margin = unit(c(0, 0, 0, 0), "cm"))
  }
  
  ## bar plot
  if(pct == T) n_table = n_table/(rowSums(n_table) + 0.1^8)
  
  ntable = as.data.frame(n_table)
  var1.levels = levels(ntable$Var1)
  if(sort.numeric) ntable$Var1 = factor(ntable$Var1, levels = sort(as.numeric(var1.levels)))
  p = ggplot(ntable, aes(x = Var1, y = Freq, fill = Var2)) +
    geom_bar(stat="identity", color = "black") +
    theme_minimal_hgrid(12) + 
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm")) 
  if(ncol(n_table) <= 3){
    colors = c("#5CBEDE", "#8DD07F", "#F95E64")
    p = p + scale_fill_manual(values = colors,
                              name = legendlab)
    p_e = p_e + scale_fill_manual(values = colors)
  }else{
    mycolors = colorRampPalette(brewer.pal(8, "Spectral"))(ncol(n_table))
    p = p + scale_fill_manual(values = mycolors, name = legendlab)
    p_e = p_e + scale_fill_manual(values = mycolors)
  }
  
  if(!is.null(xlab)) p = p + labs(x = xlab)
  if(!is.null(ylab)) p = p + labs(y = ylab)
  if(rotate.x) p = p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
  if(annot){
    p = plot_grid(NULL,
                  plot_grid(ggpubr::ggarrange(p_annot, NULL, NULL,  
                                              NULL, NULL, NULL, 
                                              p + theme(legend.position = "none"), NULL, p_e,
                                              ncol = 3, nrow = 3, align = "hv",
                                              heights = c(0.27, -0.14, 1), 
                                              widths = c(nrow(n_table), -0.1*nrow(n_table), 
                                                         0.2 + 0.15 * nrow(n_table))),
                            NULL, get_legend(p), NULL, ncol = 4, rel_widths = c(4, .1, .3, .1)),
                  NULL, ncol = 1, rel_heights = c(0.1, 3, 0.1))
  }else{
    p = plot_grid(NULL,
                  plot_grid(
                    plot_grid(p + theme(legend.position = "none"), p_e,
                              align = "h", ncol = 2, 
                              rel_widths = c(nrow(n_table), 2)),  
                    NULL, get_legend(p), NULL, ncol = 4, rel_widths = c(4, .1, .3, .1)),
                  NULL, ncol = 1, rel_heights = c(0.1, 3, 0.1))
  }
  return(p)
}


#' make plots of interested genes
#' @param seurat.obj seurat objects; 
#' @param iden.use string; column name of seurat.obj@matadata that should be used
#' as idents of the plots
#' @param genes vector of strings; a vector of interested genes
#' @param n.col integer; number of columns of ridgeplot
#' @return { a list of ggplots:ridgePlot, dotPlot, doHeatmap}  
markers_plot = function(seurat.obj, iden.use = NULL, genes, n.col = 2,
                        make.ridgePlot = T, make.dotplot = T, 
                        make.heatmap = T, make.featurePlot = T){
  if(!is.null(iden.use)) Idents(seurat.obj) = iden.use
  p = list()
  if(make.ridgePlot){
    pr = RidgePlot(seurat.obj, features = genes, ncol = n.col)
    p = append(p, list(ridgePlot = pr))
  }
  if(make.dotplot){
    pd = DotPlot(seurat.obj, features = genes) + RotatedAxis()
    p = append(p, list(dotPlot = pd))
  }
  if(make.heatmap){
    pdh = DoHeatmap(seurat.obj, features = genes, cells = 1:500, size = 4, angle = 90) + NoLegend()
    p = append(p, list(dotHeatmap = pdh))
  }
  if(make.featurePlot){
    pf = FeaturePlot(seurat.obj, features = genes, label = T)
    p = append(p, list(featurePlot = pf))
  }
  return(p)
}


#' investigate sub clusters
#' @param seurat.obj seurat object
#' @param res numeric; resolution of sub cluster
#' @param use.cols vector; vector of string; column names of columns to investigate
#' @param color_by_col vector; vector of T/F; indicates the corresponding cols 
#' from use.cols should be plot as color or not
#' @param rotate.x vector; vector of T/F; indicates whether rotate x.axis names of 
#' the corresponding cols from use.cols
#' @param harmony T/F; plot based on harmony integration or not
#' default F; plot based on CCA integration
#' @param p_annot_label vector 
#' @param remove_donor_subc T/F; whether remove donor specific clusters
plot_subcluster = function(seurat.obj, res = 0.1, 
                           use.cols = c("Donor.ID", "B", "Sex", "E"), 
                           color_by_col = c(T,F,F,F),
                           rotate.x = c(T,F,F,F), harmony = F, 
                           p_annot_label = c("", "B", "", ""),
                           remove_donor_subc = T){
  pl = list()
  
  ## if integrated by harmony
  if(harmony){
    clust_col = paste0("RNA_snn_res.", res)
  }else{
    clust_col = paste0("integrated_snn_res.", res)
  }
  
  ## if remove donor specific subclusters
  if(remove_donor_subc){
    sel_subc = find_donor_subc(seurat.obj, res)$sel.clust
  }else{
    sel_subc = unique(seurat.obj[[clust_col]])
  }
  
  if(length(color_by_col)!=length(use.cols)){
    stop("check the length of vars & color_by_col")
  }else{
    for(i in 1:length(use.cols)){
      if(!color_by_col[i]){
        n_table = table(seurat.obj[[clust_col]][,1], seurat.obj[[use.cols[i]]][,1])
        n_table = n_table[rownames(n_table) %in% sel_subc, ]
        pl[[use.cols[i]]] = freq_barplot(n_table = n_table,
                                         xlab = "cluster", ylab = "proportion", legendlab = use.cols[i], 
                                         p_annot_label = p_annot_label[i], rotate.x = rotate.x[i])
      }else{
        n_table = table(seurat.obj[[use.cols[i]]][,1],seurat.obj[[clust_col]][,1])
        n_table = n_table[, colnames(n_table) %in% sel_subc]
        pl[[use.cols[i]]] = freq_barplot(n_table = n_table,
                                         xlab = use.cols[i], ylab = "proportion", legendlab = "cluster", 
                                         p_annot_label = p_annot_label[i], annot = F, rotate.x = rotate.x[i])
      }
      
    }
  }
  return(pl)
}


#' plot gene expression from normalized counts
#' @param gene string; gene name to plot
#' @param countsn arr; 3d array [genes, subjects, cell-types]
#' generated by counts_n_ctype()
boxplot_gene_from_counts_n = function(gene, countsn, B = T){
  countsn_gene = df_to_dt(as.data.frame(countsn[gene, ,]), rowcol = "Donor.ID")
  countsn_gene_p = melt(countsn_gene, id.vars = "Donor.ID")
  setnames(countsn_gene_p, c("variable", "value"), c("cluster", "normalized.c"))
  countsn_gene_p = countsn_gene_p[ind_meta, on = .(Donor.ID)]
  if(B){
    p = ggplot(countsn_gene_p, aes(x = B, y = normalized.c, fill = B)) +
      geom_boxplot() +
      labs(title = gene, x = "")
  }else{
    p = ggplot(countsn_gene_p, aes(x = cluster, y = normalized.c, fill = B)) +
      geom_boxplot() +
      labs(title = gene, x = "")
  }
  return(p)
}


#' plot number of cells from each Donor
#' @param harmony 
ncell_per_donor = function(seurat.obj, res, ind_meta, harmony = F){
  # number of cells from each Donor
  if(harmony){
    n_table = table(seurat.obj$Donor.ID, seurat.obj@meta.data[, paste0("RNA_snn_res.",res)])
  }else{
    n_table = table(seurat.obj$Donor.ID, seurat.obj@meta.data[, paste0("integrated_snn_res.",res)])
  }
  n_table = as.data.frame(n_table)
  n_table$Var1 = factor(n_table$Var1, levels = sort(as.numeric(levels(n_table$Var1))))
  setDT(n_table)
  n_table[ind_meta, on = c("Var1" = "Donor.ID"), B := i.B]
  p = ggplot(n_table) +
    geom_bar(aes(x = Var1, y = Freq, fill = B), stat="identity", color = "black") +
    facet_grid(Var2 ~ B, scales = "free", space = "free_x") +
    labs(x = "Donor ID", y = "number of cells") +
    theme_minimal_hgrid(12) + 
    scale_fill_manual(values=c("#5CBEDE", "#8DD07F", "#F95E64")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  
  return(p)
}

#' number of high UMIs cells
#' @param seurat.obj seurat objects
#' @param res numeric; resolution of subcluster
#' @param harmony T/F; 
ncell_per_subc = function(seurat.obj, res, harmony = F){
  seurat.obj$nCount_RNA_region = ifelse(seurat.obj$nCount_RNA > 20000, ">20000", "<20000")
  if(harmony){
    n_table = table(seurat.obj$nCount_RNA_region, 
                    unlist(seurat.obj[[paste0("RNA_snn_res.", res)]]))
  }else{
    n_table = table(seurat.obj$nCount_RNA_region, 
                    unlist(seurat.obj[[paste0("integrated_snn_res.", res)]]))
  }
  p = freq_barplot(n_table = n_table, 
                   sort.numeric = F, pct = F,
                   xlab = "cluster", ylab = "number of cells") +
    facet_wrap(~ Var2, ncol = 4, scales = "free") +
    theme_minimal_hgrid(12) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  return(p)
}


#' plot HVGs from 
#' 
plot_HVGs = function(seurat.obj){
  # Identify the 10 most highly variable genes
  top10 = head(VariableFeatures(seurat.obj), 10)
  
  # plot variable features with and without labels
  plot1 = VariableFeaturePlot(seurat.obj)
  plot2 = LabelPoints(plot = plot1, points = top10, repel = TRUE)
  return(plot2)
}


#' plot a list of PC split by B
#' @param pc_cells data.table; in shape of [cells, PCs]
#' must include B (Braak stage)
#' @param pcs vector; PC indexes
#' @param density T/F; density plot if T. violin plot if F.
#' default F
#' @param alpha numeric; alpha; default 0.4
#' @param ncol numeric; number of column in plot
plot_pcs_group_by_B = function(pc_cells, pcs, density = T, alpha = 0.4, ncol = 2){
  n_pcs = length(pcs)
  plist = lapply(pcs, function(pc){
    plot_pc_group_by_B(pc_cells, pc, density, alpha)
  })
  return(do.call("grid.arrange", c(plist, ncol=ncol)))
}


#' plot PC split by B
#' @param pc_cells data.table; in shape of [cells, PCs]
#' must include B (Braak stage)
#' @param pc numeric; PC index
#' @param density T/F; density plot if T. violin plot if F.
#' default T
#' @param alpha numeric; alpha; default 0.4
plot_pc_group_by_B = function(pc_cells, pc, density = T, alpha = 0.4){
  if(density){
    return(ggplot(pc_cells, aes_string(x = paste0("PC_", pc))) +
             geom_density(aes(fill = B), alpha = alpha)  +
             theme_minimal_hgrid())
  }else{
    return(ggplot(pc_cells, aes_string(x = "B", y = paste0("PC_", pc))) +
             geom_violin(aes(fill = B), alpha = alpha)  +
             theme_minimal_hgrid())
  }
}

#' emulate default ggplot color palette
#' @param n number of colors
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

#' dimplot of a given resolution
#' @param seurat.obj seurat object;
#' @param res numeric; resolution; 
#' @param clusters vector; vector of cluster number;
dimplot_res = function(seurat.obj, res, harmony = F, colors = NULL){
  if(harmony){
    clust = paste0("RNA_snn_res.", res)
  }else{
    clust = paste0("integrated_snn_res.", res)
  }
  
  n_subc = length(unique(seurat.obj[[clust]][,1]))
  # cat("number of cluster: ", n_subc, "\n")
  
  p = DimPlot(seurat.obj, group.by = clust) +
    labs(title = paste0("resolution ", res)) +
    theme_pander() +
    theme(axis.title.y = element_blank(), axis.title.x = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          panel.background = element_blank(),
          plot.title = element_blank())
  
  # colors
  if(length(colors)==0){
    colors <- gg_color_hue(n=n_subc)
  }
  p = p + scale_color_manual(values = colors)
  return(list(p = p, colors = colors))
}


#' dimplot of interested cluster
#' @param seurat.obj seurat object;
#' @param res numeric; resolution; 
#' @param clusters vector; vector of cluster number;
dimplot_subc = function(seurat.obj, res, clusters, colors = NULL, harmony = F){
  # which clusters to plot
  if(harmony){
    subcs = as.character(levels(seurat.obj[[paste0("RNA_snn_res.", res)]][,1]))
  }else{
    subcs = as.character(levels(seurat.obj[[paste0("integrated_snn_res.", res)]][,1]))
  }
  
  if(length(colors) == 0){
    p_res = dimplot_res(seurat.obj, res, harmony = harmony)
    colors = p_res$colors
  }else{
    p_res = dimplot_res(seurat.obj, res, harmony = harmony, colors = colors)
  }
  
  gray_subcs = setdiff(subcs, clusters)
  idx = match(gray_subcs, subcs)
  colors[idx] = "#E8E7E6"
  
  p_subc = dimplot_res(seurat.obj, res, harmony = harmony, colors = colors)$p +
    theme(axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.line.y.left = element_blank())
  p = plot_grid(p_res$p + theme(legend.position = "none", plot.margin = unit(c(0,0,0,0), "lines")),
                p_subc + theme(legend.position = "none", plot.margin = unit(c(0,0,0,0), "lines")), 
                NULL, get_legend(p_res$p),
                rel_widths = c(3,2.7,0.1, 0.5), ncol = 4)
  y.grob = textGrob("UMAP2", rot=90)
  x.grob = textGrob("UMAP1")
  p = grid.arrange(arrangeGrob(p, left = y.grob, bottom = x.grob))
  
  return(p)
}


#' plot heatmap based on chunk of select genes
#' @param seurat.obj seurat object
#' @param genes vector; vector of plot genes
#' @param chunks vector; groups of genes; same length as genes
do_heatmap_chunk = function(seurat.obj, genes, chunks, yax_text = T){
  require(ggpubr)
  cat("heatmap based on RNA assay...\n")
  DefaultAssay(seurat.obj) = "RNA"
  chunk_u = unique(chunks)
  suppressMessages({
    pl_all = lapply(1:length(chunk_u), function(idx){
      chunk = chunk_u[idx]
      chunk_gene = genes[chunks == chunk]
      if(idx == 1){
        p = do_heatmap_gene(seurat.obj, chunk_gene) +
          NoLegend() +
          labs(y = chunk, x = NULL) + theme(plot.margin = unit(c(0,0,0,0), "lines"))
      }else{
        p = do_heatmap_gene_no_col_bar(seurat.obj, chunk_gene) +
          NoLegend() +
          labs(y = chunk) + theme(plot.margin = unit(c(0,0,0,0), "lines"))
      }
      
      if (!yax_text) {
        p = p +
          theme(axis.text.y=element_blank())
      }
      height = sum(chunks == chunk)
      return(list(p = p, height = height))
    })
  })
  pl = lapply(pl_all, function(x) x$p)
  heights = unlist(lapply(pl_all, function(x) x$height))
  p = ggarrange(plotlist = pl, ncol = 1, heights = heights, align = "v")
  return(p)
}


#' plot heatmap based on chunk of select genes
#' @param seurat.obj seurat object
#' @param annot data.table; data table of a list of interested genes 
do_heatmap_gene = function(seurat.obj, genes){
  DefaultAssay(seurat.obj) = "RNA"
  suppressMessages({
    p = DoHeatmap(seurat.obj,
                  features = genes,
                  lines.width = 15) +
      scale_fill_gradient2(low="#278fa6", mid="white", high="#fa0526", na.value = "white")
  })
  return(p)
}


#' plot heatmap based on chunk of select genes
#' @param seurat.obj seurat object
#' @param annot data.table; data table of a list of interested genes 
do_heatmap_gene_no_col_bar = function(seurat.obj, genes){
  DefaultAssay(seurat.obj) = "RNA"
  suppressMessages({
    p = DoHeatmap(seurat.obj,
                  features = genes,
                  lines.width = 15,
                  group.bar = F) +
      scale_fill_gradient2(low="#278fa6", mid="white", high="#fa0526", na.value = "white")
  })
  return(p)
}


#' subcluster 
#' @param n_table matrix; proportion of Braak stage
#' [B, subc)]
subc_statis_test = function(n_table, label){
  ## chi-sqaure test
  chisq_table = chisq_test(n_table)
  chisq_table = melt(df_to_dt(data.frame(chisq_table), rowcol = "B"), id.vars = "B", variable.name = "cluster", value.name = "greater")
  chisq_table[, cluster := as.factor(gsub("^X", "", cluster))]
  chisq_table[, B := paste0(label, B)]
  ## binominal test
  ### p value
  binom = binomial_test(n_table)
  binom_p = binom$p
  binom_p = melt(df_to_dt(data.frame(binom_p), rowcol = "B"), id.vars = "B", variable.name = "cluster", value.name = "p.value")
  binom_p[, cluster := as.factor(gsub("^X", "", cluster))]
  binom_p[, B := paste0(label, B)]
  binom_p[, binom_sig := ifelse(p.value > 0.05, "", "*")]
  ### fc = observed proportion / expected proportion
  binom_fc = binom$fc
  binom_fc = melt(df_to_dt(data.frame(binom_fc), rowcol = "B"), id.vars = "B", variable.name = "cluster", value.name = "fc")
  binom_fc[, cluster := as.factor(gsub("^X", "", cluster))]
  binom_fc[, B := paste0(label, B)]
  binom_p[binom_fc, on =.(B, cluster), fc := i.fc]
  ## merge
  chisq_table[binom_p, on =.(B, cluster), c("binom_sig", "fc") := .(i.binom_sig, i.fc)]
  chisq_table[, fc := paste(fc, binom_sig)]
  chisq_table$B = factor(chisq_table$B, levels = sort(levels(factor(chisq_table$B)), decreasing = T))
  
  ## heatmap
  p = ggplot(chisq_table, aes(y = B, x = cluster, fill = greater)) + 
    geom_tile() +
    geom_text(aes(label = fc), size = 2.4) +
    theme_few() + 
    theme(legend.position = "none",
          plot.margin = unit(c(0, 0, 0, 0), "cm"), 
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          axis.line = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.text.y = element_text(colour = "black", size = 7)) + 
    scale_fill_manual(values=c("#FA8486", "white"))
  return(p)
}


#' vlnplot
#' @param genes
#' @param obj
vln_plot = function(obj, gene){
  p = VlnPlot(ast_CCA_removed, features = gene, pt.size = 0) + 
    scale_fill_manual(values=c("#F5CD48", "#7FD2B7", "#FA8E69", "#90E3DC", "#4D879E", #"#4F9E22", 
                               "#7DC500", "#D84434", "#825D67"))
  return(p)
}


#' co express of 2 genes
#' @gene1
#' @gene2
coexpress_count2 = function(counts, gene1, gene2, celltypes){
  counts_sel = counts[c(gene1, gene2), ]
  dat = data.table(tag = colnames(counts),
                   gene1.c = counts[gene1,],
                   gene2.c = counts[gene2,],
                   celltypes = celltypes)
  dat[dat[, .N, by = .(gene1.c, gene2.c, celltypes)], on = .(gene1.c, gene2.c), num := i.N]
  p = ggplot(dat, aes(x = gene1.c, y = gene2.c, color = num)) +
    geom_point() +
    facet_wrap(~ celltypes, ncol = 2) +
    ggthemes::theme_few() +
    labs(x = gene1, y = gene2)
  return(p)
}

#' Plot number of nuclei per subcluster
#' @param seurat.obj seurat object (e.g. CCA-integrated endothelial cells)
#' @param plot_dir output directory for ggplot
#' @param dataset_name name of dataset
#' @res clustering resolution
plot_nuclei_per_subcluster <- function(seurat.obj, plot_dir, 
                                       dataset_name="Endothelial_Data1", res=0.3) {
  
  
  num_cells_by_cluster <- data.frame(Cluster=seurat.obj[[paste0("integrated_snn_res.",res)]]) %>%
    remove_rownames() %>%
    rename("Cluster"=paste0("integrated_snn_res.",res)) %>%
    mutate(Number_Nuclei = n()) %>%
    group_by(Cluster, Number_Nuclei) %>%
    summarise(Num_Nuc_in_Cluster=n()) %>%
    ungroup() %>%
    mutate(total_num_nuc = sum(Num_Nuc_in_Cluster)) %>%
    group_by(Cluster, Number_Nuclei, Num_Nuc_in_Cluster) %>%
    summarise(Percent_Total_Nuclei = round(100*Number_Nuclei/total_num_nuc, 1)) 
  
  total_num_end_cells <- sum(num_cells_by_cluster$Num_Nuc_in_Cluster)
  num_cells_by_cluster %>%
    ggplot(data=., mapping=aes(x=Cluster, y=Num_Nuc_in_Cluster, fill=Cluster)) +
    geom_text(aes(label=Num_Nuc_in_Cluster, color=Cluster),
              position=position_dodge(width=0.9), vjust=-0.25) +
    geom_bar(stat="identity", position="dodge") +
    theme_bw() +
    ylab("Number of Nuclei in Cluster") +
    scale_y_continuous(sec.axis = sec_axis(~(.*100)/total_num_end_cells, 
                                           name = "Percent of Total Nuclei"),
                       expand=c(0,0,0.1,0)) +
    ggtitle(sprintf("Number of %s Nuclei\nby Subcluster at Resolution %s", 
                    dataset_name, res)) +
    theme(legend.position="none",
          plot.title=element_text(hjust=0.5))
  
  ggsave(paste0(plot_dir, sprintf("%s_num_cells_clusters_res%s.png",
                                  dataset_name, res), sep=""),
         width=6, height=4, units="in", dpi=300)
}

#' Plot proportion of cells in each subcluster by subject, arranged by pTau/tau ratio
#' @param seurat.obj seurat object (e.g. CCA-integrated endothelial cells)
#' @param plot_dir output directory for ggplot
#' @param dataset_name name of dataset
#' @res clustering resolution
plot_nuclei_per_subcluster_by_subj_ptau <- function(seurat.obj, plot_dir,
                                                    dataset_name="Endothelial_Data1",
                                                    res=0.3) {
  
  ptau_tau_bar <- data.frame(pTau_to_Tau = seurat.obj@meta.data$Ptau.Total.Tau..A.U..,
                             Donor.ID = seurat.obj@meta.data$Donor.ID) %>%
    distinct() %>%
    ggplot(data=., mapping=aes(x=fct_reorder(Donor.ID, pTau_to_Tau, .desc=T),
                               y=pTau_to_Tau)) +
    geom_bar(stat="identity")  +
    theme_bw() +
    ylab("pTau-Tau Ratio") +
    xlab("Donor") +
    theme(axis.text.x=element_blank(),
          axis.title.x=element_blank(),
          axis.ticks.x=element_blank())
  
  cluster_props <- data.frame(Cluster=seurat.obj[[paste0("integrated_snn_res.",res)]],
                              pTau_to_Tau = seurat.obj@meta.data$Ptau.Total.Tau..A.U..,
                              Donor.ID = seurat.obj@meta.data$Donor.ID) %>%
    remove_rownames() %>%
    rename("Cluster"=paste0("integrated_snn_res.", res)) %>%
    group_by(Donor.ID, pTau_to_Tau, Cluster) %>%
    summarise(n_nuc = n()) %>%
    group_by(Donor.ID, pTau_to_Tau) %>%
    mutate(total_num_nuc = sum(n_nuc),
           cluster_prop = n_nuc / total_num_nuc) %>%
    ggplot(data=., mapping=aes(x=fct_reorder(Donor.ID, pTau_to_Tau, .desc=T), 
                               y=cluster_prop, fill=Cluster)) +
    geom_bar(stat="identity", color="black") +
    theme_bw() +
    ylab("Cluster Proportion") +
    xlab("Donor") +
    theme(axis.text.x=element_text(angle=90))
  
  ptau_tau_bar / cluster_props
  ggsave(paste0(plot_dir, sprintf("%s_cluster_props_by_ptau_tau_res%s.png",
                                  dataset_name, res), sep=""), width=6, height=5, 
         units="in", dpi=300)
}


#' Plot proportion of Braak stage nuclei per subcluster, along with expected proportions
#' @param seurat.obj seurat object (e.g. CCA-integrated endothelial cells)
#' @param plot_dir output directory for ggplot
#' @param dataset_name name of dataset
#' @res clustering resolution
plot_nuclei_per_subcluster_by_braak <- function(seurat.obj, 
                                                metadata_df,
                                                brain_region,
                                                dataset_name,
                                                plot_dir,
                                                res=0.3,
                                                width=6,
                                                height=4) {
  
  # remove any donor-specific clusters
  seurat_clean <- removd_donor_clust(seurat.obj, res=res)
  
  # remove ABC-B column
  seurat_wo_braak <- seurat_clean@meta.data %>% select(-B)
  
  # calculate expected ABC-B proportions for a generic cluster
  expected_braak_proportions <- seurat_wo_braak %>% 
    select(Donor.ID, paste0("integrated_snn_res.", res)) %>%
    rename("Subcluster" = paste0("integrated_snn_res.", res)) %>%
    left_join(., metadata_df) %>%
    filter(!is.na(B)) %>%
    mutate(all_nuclei_count = n()) %>%
    group_by(B) %>%
    summarise(Subcluster_Braak_proportion = n()/all_nuclei_count) %>%
    distinct() %>%
    mutate(Subcluster="Expected",
           Subcluster_Type="Expected")
  
  seurat_wo_braak %>% select(Donor.ID, paste0("integrated_snn_res.", res)) %>%
    left_join(., metadata_df) %>%
    filter(!is.na(B)) %>%
    rename("Subcluster" = paste0("integrated_snn_res.", res)) %>%
    mutate(all_nuclei_count = n()) %>%
    group_by(Subcluster) %>%
    mutate(total_cluster_size=n()) %>%
    group_by(Subcluster, total_cluster_size, B) %>%
    summarise(Subcluster_Braak_proportion = n()/total_cluster_size,
              Subcluster_Type="Actual") %>%
    distinct() %>%
    plyr::rbind.fill(., expected_braak_proportions) %>%
    ungroup() %>%
    mutate(Subcluster = factor(Subcluster, levels=c(sort(unique(as.numeric(Subcluster))),
                                                    "Expected"))) %>%
    ggplot(data=., mapping=aes(x=Subcluster, y=Subcluster_Braak_proportion, fill=B)) +
    geom_bar(stat="identity", color="black") +
    facet_grid(. ~ Subcluster_Type, scales="free", space="free") +
    ggtitle(sprintf("Proportion of %s Endothelial Subcluster Nuclei\nby Braak Stage at Resolution %s", 
                    brain_region, res)) +
    theme_bw() +
    xlab("Cluster") +
    labs(fill="ABC-B") +
    scale_fill_manual(values=c("seagreen3", "gold2", "indianred2")) +
    ylab("Nuclei Proportion") +
    theme(strip.background = element_blank(),
          strip.text.x = element_blank(),
          plot.title=element_text(hjust=0.5),
          axis.text=element_text(size=12))
  
  ggsave(paste0(plot_dir, sprintf("%s_%s_Braak_aggregated_subcluster_props_res%s.png",
                                  brain_region, dataset_name, res), sep=""),
         width=width, height=height, units="in", dpi=300)
}

#' Plot proportion of Braak stage nuclei per subcluster, along with expected proportions
#' @param seurat.obj seurat object (e.g. CCA-integrated endothelial cells)
#' @param plot_dir output directory for ggplot
#' @param dataset_name name of dataset
#' @res clustering resolution
plot_nuclei_per_subcluster_by_amyloid <- function(seurat.obj, 
                                                metadata_df,
                                                brain_region,
                                                dataset_name,
                                                plot_dir,
                                                res=0.3,
                                                width=6,
                                                height=4) {
  
  # remove any donor-specific clusters
  seurat_clean <- removd_donor_clust(seurat.obj, res=res)
  
  # remove ABC-A column
  seurat_wo_amyloid <- seurat_clean@meta.data %>% select(-A)
  
  # calculate expected ABC-A proportions for a generic cluster
  expected_amyloid_proportions <- seurat_wo_amyloid %>% 
    select(Donor.ID, paste0("integrated_snn_res.", res)) %>%
    rename("Subcluster" = paste0("integrated_snn_res.", res)) %>%
    left_join(., metadata_df) %>%
    filter(A != "unk") %>%
    mutate(A = case_when(A %in% c("0", "1") ~ "1",
                         T ~ A),
           all_nuclei_count = n()) %>%
    group_by(A) %>%
    summarise(Subcluster_Amyloid_proportion = n()/all_nuclei_count) %>%
    distinct() %>%
    mutate(Subcluster="Expected",
           Subcluster_Type="Expected")
  
  seurat_wo_amyloid %>% select(Donor.ID, paste0("integrated_snn_res.", res)) %>%
    left_join(., metadata_df) %>%
    filter(A != "unk") %>%
    mutate(A = case_when(A %in% c("0", "1") ~ "1",
                         T ~ A),
           all_nuclei_count = n()) %>%
    rename("Subcluster" = paste0("integrated_snn_res.", res)) %>%
    mutate(all_nuclei_count = n()) %>%
    group_by(Subcluster) %>%
    mutate(total_cluster_size=n()) %>%
    group_by(Subcluster, total_cluster_size, A) %>%
    summarise(Subcluster_Amyloid_proportion = n()/total_cluster_size,
              Subcluster_Type="Actual") %>%
    distinct() %>%
    plyr::rbind.fill(., expected_amyloid_proportions) %>%
    ungroup() %>%
    mutate(Subcluster = factor(Subcluster, levels=c(sort(unique(as.numeric(Subcluster))),
                                                    "Expected"))) %>%
    ggplot(data=., mapping=aes(x=Subcluster, y=Subcluster_Amyloid_proportion, fill=A)) +
    geom_bar(stat="identity", color="black") +
    facet_grid(. ~ Subcluster_Type, scales="free", space="free") +
    ggtitle(sprintf("Proportion of %s Endothelial Subcluster Nuclei\nby Amyloid Stage at Resolution %s", 
                    brain_region, res)) +
    theme_bw() +
    xlab("Cluster") +
    labs(fill="ABC-A") +
    scale_fill_manual(values=c("seagreen3", "gold2", "indianred2")) +
    ylab("Nuclei Proportion") +
    theme(strip.background = element_blank(),
          strip.text.x = element_blank(),
          plot.title=element_text(hjust=0.5),
          axis.text=element_text(size=12))
  
  ggsave(paste0(plot_dir, sprintf("%s_%s_Amyloid_aggregated_subcluster_props_res%s.png",
                                  brain_region, dataset_name, res), sep=""),
         width=width, height=height, units="in", dpi=300)
}


#' Plot correlation between cluster proportion and pTau/tau ratio
#' @param seurat.obj seurat object (e.g. CCA-integrated endothelial cells)
#' @param brain_region name of brain region (e.g. "BA20")
#' @param dataset_name name of specific dataset (e.g. "endothelial_subc_filtered")
#' @param res cluster resolution
#' @param plot_dir output directory for ggplot
#' @param ncol number of columns for output
#' @param width width (inches) of resulting png image
#' @param height height (inches) of resulting png image
plot_cluster_ptau_prop_corr <- function(seurat.obj,
                                        brain_region,
                                        dataset_name,
                                        plot_dir,
                                        res=0.3, 
                                        ncol=2, width=6, height=8) {
  
  # remove any donor-specific clusters if they are present
  seurat.clean <- removd_donor_clust(seurat.obj, res=res)
  
  plot <- seurat.clean@meta.data %>%
    select(Donor.ID, paste0("integrated_snn_res.", res),
           Ptau.Total.Tau..A.U..) %>%
    rename("Cluster" = paste0("integrated_snn_res.", res),
           "pTau_to_Tau" = "Ptau.Total.Tau..A.U..") %>%
    mutate(clustlabels = paste0("Cluster ", Cluster)) %>%
    group_by(Cluster) %>%
    mutate(total_num_cells_cluster=n()) %>%
    group_by(Donor.ID) %>%
    mutate(total_num_cells_donor=n()) %>%
    group_by(Donor.ID, pTau_to_Tau, Cluster) %>%
    summarise(cluster_prop_by_donor = n()/total_num_cells_donor,
              num_cells = total_num_cells_cluster) %>%
    mutate(facet_label = paste0("Cluster ", Cluster, ", # Cells: ", num_cells)) %>%
    mutate(facet_label = factor(facet_label,
                                levels=mixedsort(unique(facet_label)))) %>%
    distinct() %>%
    ggplot(data=., mapping=aes(x=pTau_to_Tau, y=cluster_prop_by_donor)) +
    geom_point() +
    geom_smooth(method=lm, se=FALSE, fullrange=TRUE, color='2C3E50') +
    ggtitle(sprintf("%s Endothelial Cluster Proportions\nvs. pTau/Tau Ratio",
                    brain_region)) +
    ylab("# Nuclei in Cluster vs. Total  Donor Nuclei") +
    xlab("pTau / Total Tau") +
    facet_wrap(facet_label ~ ., ncol=ncol, scales="free", labeller = labeller(label_both)) +
    stat_cor(method = "spearman", color="red") +
    theme_minimal() +
    theme(strip.text = element_text(size=12),
          axis.title=element_text(size=12),
          plot.title=element_text(hjust=0.5))
  ggsave(paste(plot_dir, sprintf("%s_%s_ptau_tau_res%s_correlation.png", brain_region,
                                 dataset_name, res)
               , sep=""), dpi=300,
         width=width, height=height, units="in")
}

#' Plot correlation between cluster proportion and HEK seeding
#' @param seurat.obj seurat object (e.g. CCA-integrated endothelial cells)
#' @param brain_region name of brain region (e.g. "BA20")
#' @param dataset_name name of specific dataset (e.g. "endothelial_subc_filtered")
#' @param res cluster resolution
#' @param plot_dir output directory for ggplot
#' @param ncol number of columns for output
#' @param width width (inches) of resulting png image
#' @param height height (inches) of resulting png image
plot_cluster_hek_seeding_prop_corr <- function(seurat.obj,
                                        brain_region,
                                        dataset_name,
                                        plot_dir,
                                        res=0.3, 
                                        ncol=2, width=6, height=8) {
  
  # remove any donor-specific clusters if they are present
  seurat.clean <- removd_donor_clust(seurat.obj, res=res)
  
  plot <- seurat.clean@meta.data %>%
    select(Donor.ID, paste0("integrated_snn_res.", res),
           HEK.SEEDING..IFD.) %>%
    rename("Cluster" = paste0("integrated_snn_res.", res),
           "HEK_Seeding" = "HEK.SEEDING..IFD.") %>%
    mutate(clustlabels = paste0("Cluster ", Cluster)) %>%
    group_by(Cluster) %>%
    mutate(total_num_cells_cluster=n()) %>%
    group_by(Donor.ID) %>%
    mutate(total_num_cells_donor=n()) %>%
    group_by(Donor.ID, HEK_Seeding, Cluster) %>%
    summarise(cluster_prop_by_donor = n()/total_num_cells_donor,
              num_cells = total_num_cells_cluster) %>%
    mutate(facet_label = paste0("Cluster ", Cluster, ", # Cells: ", num_cells)) %>%
    mutate(facet_label = factor(facet_label,
                                levels=mixedsort(unique(facet_label)))) %>%
    distinct() %>%
    ggplot(data=., mapping=aes(x=HEK_Seeding, y=cluster_prop_by_donor)) +
    geom_point() +
    geom_smooth(method=lm, se=FALSE, fullrange=TRUE, color='2C3E50') +
    ggtitle(sprintf("%s Endothelial Cluster Proportions\nvs. HEK Seeding",
                    brain_region)) +
    ylab("# Nuclei in Cluster vs. Total  Donor Nuclei") +
    xlab("HEK Seeding") +
    facet_wrap(facet_label ~ ., ncol=ncol, scales="free", labeller = labeller(label_both)) +
    stat_cor(method = "spearman", color="red") +
    theme_minimal() +
    theme(strip.text = element_text(size=12),
          axis.title=element_text(size=12),
          plot.title=element_text(hjust=0.5))
  ggsave(paste(plot_dir, sprintf("%s_%s_HEK_seeding_res%s_correlation.png", brain_region,
                                 dataset_name, res)
               , sep=""), dpi=300,
         width=width, height=height, units="in")
}

#' Plot correlation between cluster proportion and percent amyloid plaque positive tissue (DAB staining)
#' @param seurat.obj seurat object (e.g. CCA-integrated endothelial cells)
#' @param brain_region name of brain region (e.g. "BA20")
#' @param dataset_name name of specific dataset (e.g. "endothelial_subc_filtered")
#' @param res cluster resolution
#' @param plot_dir output directory for ggplot
#' @param ncol number of columns for output
#' @param width width (inches) of resulting png image
#' @param height height (inches) of resulting png image
plot_cluster_amyloid_prop_corr <- function(seurat.obj,
                                           amyloid_metadata,
                                           brain_region,
                                           dataset_name,
                                           plot_dir,
                                           res=0.3, 
                                           ncol=2, width=6, height=8) {
  
  # remove any donor-specific clusters if they are present
  seurat.clean <- removd_donor_clust(seurat.obj, res=res)
  
  plot <- seurat.clean@meta.data %>%
    select(Donor.ID, paste0("integrated_snn_res.", res)) %>%
    rename("ADRC" = "Donor.ID",
           "Cluster" = paste0("integrated_snn_res.", res)) %>%
    mutate(Region=brain_region) %>%
    left_join(., amyloid_metadata) %>%
    mutate(clustlabels = paste0("Cluster ", Cluster)) %>%
    group_by(Cluster) %>%
    mutate(total_num_cells_cluster=n()) %>%
    group_by(ADRC) %>%
    mutate(total_num_cells_donor=n()) %>%
    group_by(ADRC, percent_DAB_positive_tissue, Cluster) %>%
    summarise(cluster_prop_by_donor = n()/total_num_cells_donor,
              num_cells = total_num_cells_cluster) %>%
    mutate(facet_label = paste0("Cluster ", Cluster, ", # Cells: ", num_cells)) %>%
    mutate(facet_label = factor(facet_label,
                                levels=mixedsort(unique(facet_label)))) %>%
    distinct() %>%
    ggplot(data=., mapping=aes(x=percent_DAB_positive_tissue, y=cluster_prop_by_donor)) +
    geom_point() +
    geom_smooth(method=lm, se=FALSE, fullrange=TRUE, color='2C3E50') +
    ggtitle(sprintf("%s Endothelial Cluster Proportions\nvs. %% 3D6 Amyloid Plaque-Positive Tissue",
                    brain_region)) +
    ylab("# Nuclei in Cluster vs. Total  Donor Nuclei") +
    xlab("% 3D6 DAB-Positive Tissue") +
    facet_wrap(facet_label ~ ., ncol=ncol, scales="free", labeller = labeller(label_both)) +
    stat_cor(method = "spearman", color="red") +
    theme_minimal() +
    theme(strip.text = element_text(size=12),
          axis.title=element_text(size=12),
          plot.title=element_text(hjust=0.5))
  ggsave(paste(plot_dir, sprintf("%s_%s_percent_amyloid_3D6_DAB_res%s_correlation.png", brain_region,
                                 dataset_name, res)
               , sep=""), dpi=300,
         width=width, height=height, units="in")
}


compare_gene_exp_w_filtering <- function(seurat.obj, seurat.obj.filtered, gene, plot_dir) {
  
  gene_full_end_data <- FetchData(
    object = seurat.obj,
    vars = c("UMAP_1", "UMAP_2", 'ident', gene),
    slot = "data"
  ) %>%
    mutate(Dataset="Endothelial Data1")
  
  gene_filtered_end_data <- FetchData(
    object = seurat.obj.filtered,
    vars = c("UMAP_1", "UMAP_2", 'ident', gene),
    slot = "data"
  ) %>%
    mutate(Dataset="Endothelial Data1, Filtered")
  
  plyr::rbind.fill(gene_full_end_data, gene_filtered_end_data) %>%
    rename("Gene" = as.character(gene)) %>%
    mutate(Gene = ifelse(Gene<0, 0, Gene)) %>%
    group_by(Dataset) %>%
    arrange(Gene) %>%
    ggplot(data=., mapping=aes(x=UMAP_1, y=UMAP_2, color=Gene)) +
    geom_point(size=0.5) +
    ggtitle(sprintf("%s Expression in Endothelial Cells", gene)) +
    labs(color=gene) +
    facet_grid(. ~ Dataset, scales="free", space="free") +
    scale_color_gradient(low="lightgrey", high="blue") +
    theme_bw() +
    theme(strip.placement="outside",
          plot.title=element_text(hjust=0.5))
  ggsave(paste0(plot_dir, sprintf("Endothelial_Data1_Filtered_%s_Comparison.png",
                                  gene)),
         width=8, height=3, units="in", dpi=300)
}